server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true
